### ISSUE TITLE
AI-900 Content Safety Studio & Cognitive Services Issues

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/mslearn-ai-fundamentals#20]
# Module: 01
#### Step: 00

Description of issue
I'm working through the AI900 labs and am getting the following error when trying to execute some of the sample Content Safety Studio queries.

**Your account does not have access to this resource, please contact your resource owner to get access.**

I have waited over an hour and I still do not have access. I also attempted this with my MSDN subscription, and I get the same error.
 
I have trained this course now for the past 3 weeks and it has been rather unpleasant for everyone including myself.
As a Microsoft course labs should work as expected. I've seen others commenting on things that are still not resolved weeks later. 
That is a terrible experience for our students.

Lab doesn't work at all with content studio for the first Lab.
Every other lab has a wait time of at least 10-15 min for the Access Denied Errors to stop and for the service to suddenly start working.

Repro steps:

1.Follow steps as per labs
1.Do not get results as per labs.
1.Wait for  long time for service to behave as it should.

Dane Pillay-Nel (MCT - MCT Regional Lead South Africa)

**Comment by scottrhay** [comment]
I'm experiencing the same issue when using my own Azure account (VS enterprise subscription), or when using the Skillsoft lab virtual machine. There seems to be no way around this account access error. 
I agree with Dane, this is a pretty bad experience to need to skip the very first lab in this course due to errors in it. 
Scott - MCT

**Comment by sherzyang** [comment]
@DanePillay-nel , @scottrhay , thank you for sharing and I'm very sorry it has been frustrating. The issue is on the product end, and I am working on a solution. I'll give an update when it's resolved.

**Comment by abhraloony** [comment]
Hi I am also facing the same issue while trying to use Text moderation service of  Content Safety Studio and same error i.e "Your account does not have access to this resource, please contact your resource owner to get access " is coming. When can we expect to get this resolved? Thank you

**Comment by sherzyang** [comment]
@DanePillay-nel, @scottrhay, @abhraloony, I worked with our support team and there has been a change in the product. Users will need to assign themselves "Cognitive Services User" on top of the automated "Owner" role to use their Content Safety resource. For now, I will update the instructions to include this step. Next week I'll begin working on a new lab. 

For reference, I've highlighted where to look for the roles needed in order to use the Content Safety resource as expected: 

![image](https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/assets/19577448/a3836aa9-976a-496d-8b79-69e2f84f8ccc)

**Comment by DanePillay-nel** [comment]
Thank you appreciate it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DanePillay-nel** [comment]
Hello Sherry,

I have tested as directed and have exactly the same issue as before.
Tried in an incognito browser as well.
Tried both user and contributor.
The cognitive services user /contributor don't work.

Kind Regards
Dane
________________________________

**Comment by DanePillay-nel** [comment]
Just tested again,and I can say it is indeed working again. Thank God

**Comment by DanePillay-nel** [comment]
To confirm the service is now working with the above fix of adding the permissions .

Thank you Sherry
________________________________

**Comment by scottrhay** [comment]
FYI I set up 2 exactly configured Content Safety resources and added the additional permissions. Both showed the same Current role assignments on the Settings/Resource tab in Content Safety Studio. The resource in East US worked, while the resource in East US 2 always failed with the security error. After waiting 10+ minutes, the East US 2 region resource started working too. 

FYI I'm seeing this delayed security provisioning across this service and many other services (vision, language, speech, etc.) - it's been a problem for all of the labs in my AI102 delivery this week. After deploying these resources, students will receive security errors trying to use the services in the associated studios, or programmatically, for 20+ min after the resource was deployed successfully. As with my content safety example above, it seems like this is worse in some regions. If you see this problem, I recommend trying a different region for your resources.
