### ISSUE TITLE
Deploy a model for language generation issue

### ISSUE THREAD

**Issue by ahsan296** [MicrosoftLearning/mslearn-ai-fundamentals#30]
#### Step: 03

When I perform step 2 and click the Deploy button, the attached page appears instead of showing the new deployment page. I was able to complete this lab successfully a few days ago without any issues, but now I'm encountering this problem. Please let me know when it has been resolved.

**Screen Shot:**

![image](https://github.com/user-attachments/assets/cb5938c1-b730-4a06-980c-879e9070c899)

**Comment by sherzyang** [comment]
Thanks for sharing @ahsan296, let me take a look and get back to you!

**Comment by ahsan296** [comment]
Thanks @sherzyang I will wait for your positive response.

**Comment by sherzyang** [comment]
Hi @ahsan296 I actually need to retire this lab. Please use its replacement: https://microsoftlearning.github.io/mslearn-ai-studio/Instructions/01-Explore-ai-studio.html.

I will make sure the lab instructions are updated for clarity - sorry about any confusion! The error you're getting is because the features of Azure OpenAI Studio are now housed in Azure AI Studio (which is used in the new lab).

**Comment by ahsan296** [comment]
Kindly let me know if this is the replacement for Lab 13, so we can consider it as Lab 13.

**Comment by sherzyang** [comment]
Oh yes, we should consider it as the permanent replacement for Lab 13
