### ISSUE TITLE
Module 01 Explore Automated Machine Learning in Azure Machine Learning Cannot Deploy

### ISSUE THREAD

**Issue by nugysemail** [MicrosoftLearning/mslearn-ai-fundamentals#32]
# Module: 01
#### Step: 01

Description of issue
Can not deploy End Point.
![image](https://github.com/user-attachments/assets/ddd21b1c-0e66-4048-bc7a-cb5f201fbd5c)

**Comment by sherzyang** [comment]
Hi @nugysemail, I tried to reproduce your error but couldn't. It looks like you're experiencing an issue related to your subscription's resource registration. That means your subscription currently does not provide access to the Azure ML resource, and that is blocking your model's deployment. 

If you are working from your own subscription, this tutorial may help you troubleshoot the issue: https://learn.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/error-register-resource-provider?tabs=azure-portal#solution

If you are using a virtual machine from Skillable, you could run into this error because you are only meant to complete the lab in the instruction panel in that machine. Only the resources from the lab in the instruction panel are permitted for that subscription. 

Hope that helps! If it doesn't, feel free to open another bug.
